<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="36" failed="1" ignored="0" total="40" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="4486" started-at="2017-07-05T13:13:33Z" finished-at="2017-07-05T13:13:37Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="4486" started-at="2017-07-05T13:13:33Z" finished-at="2017-07-05T13:13:37Z">
      <class name="com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase">
        <test-method status="PASS" signature="loadDatabase()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="loadDatabase" is-config="true" duration-ms="2158" started-at="2017-07-05T14:13:33Z" finished-at="2017-07-05T14:13:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadDatabase -->
        <test-method status="PASS" signature="testAddFirstElements()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testAddFirstElements" duration-ms="854" started-at="2017-07-05T14:13:35Z" finished-at="2017-07-05T14:13:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddFirstElements -->
        <test-method status="PASS" signature="cleanPendedEvents()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="cleanPendedEvents" is-config="true" duration-ms="0" started-at="2017-07-05T14:13:36Z" finished-at="2017-07-05T14:13:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanPendedEvents -->
        <test-method status="PASS" signature="testInit()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testInit" duration-ms="129" started-at="2017-07-05T14:13:36Z" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testAddFirstElements" finished-at="2017-07-05T14:13:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInit -->
        <test-method status="PASS" signature="cleanPendedEvents()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="cleanPendedEvents" is-config="true" duration-ms="1" started-at="2017-07-05T14:13:36Z" finished-at="2017-07-05T14:13:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanPendedEvents -->
        <test-method status="PASS" signature="testAllConnect()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testAllConnect" duration-ms="432" started-at="2017-07-05T14:13:36Z" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testInit" finished-at="2017-07-05T14:13:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAllConnect -->
        <test-method status="PASS" signature="cleanPendedEvents()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="cleanPendedEvents" is-config="true" duration-ms="0" started-at="2017-07-05T14:13:37Z" finished-at="2017-07-05T14:13:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanPendedEvents -->
        <test-method status="FAIL" signature="testOldElementsAddedBeforeAddingSynchroSynchronized()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testOldElementsAddedBeforeAddingSynchroSynchronized" duration-ms="93" started-at="2017-07-05T14:13:37Z" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testAllConnect" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [0] but found [2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [0] but found [2]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.distrimind.ood.database.TestDecentralizedDatabase.checkDatabaseInternalDataUsedForSynchro(TestDecentralizedDatabase.java:688)
	at com.distrimind.ood.database.TestDecentralizedDatabase.checkAllDatabaseInternalDataUsedForSynchro(TestDecentralizedDatabase.java:679)
	at com.distrimind.ood.database.TestDecentralizedDatabase.testOldElementsAddedBeforeAddingSynchroSynchronized(TestDecentralizedDatabase.java:1050)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOldElementsAddedBeforeAddingSynchroSynchronized -->
        <test-method status="PASS" signature="cleanPendedEvents()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="cleanPendedEvents" is-config="true" duration-ms="0" started-at="2017-07-05T14:13:37Z" finished-at="2017-07-05T14:13:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanPendedEvents -->
        <test-method status="SKIP" signature="testSynchroBetweenTwoPeers(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testSynchroBetweenTwoPeers" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="provideDataForSynchroBetweenTwoPeers" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testOldElementsAddedBeforeAddingSynchroSynchronized" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testSynchroBetweenTwoPeers(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testSynchroBetweenTwoPeers(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSynchroBetweenTwoPeers -->
        <test-method status="SKIP" signature="testSynchroAfterTestsBetweenTwoPeers()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testSynchroAfterTestsBetweenTwoPeers" duration-ms="0" started-at="2017-07-05T14:13:37Z" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testSynchroBetweenTwoPeers" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testSynchroAfterTestsBetweenTwoPeers()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testSynchroAfterTestsBetweenTwoPeers()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSynchroAfterTestsBetweenTwoPeers -->
        <test-method status="SKIP" signature="testSynchroBetweenThreePeers(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testSynchroBetweenThreePeers" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="provideDataSynchroBetweenThreePeers" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testSynchroBetweenTwoPeers" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testSynchroBetweenThreePeers(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testSynchroBetweenThreePeers(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSynchroBetweenThreePeers -->
        <test-method status="SKIP" signature="testSynchroAfterTestsBetweenThreePeers()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testSynchroAfterTestsBetweenThreePeers" duration-ms="0" started-at="2017-07-05T14:13:37Z" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testSynchroBetweenThreePeers" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testSynchroAfterTestsBetweenThreePeers()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testSynchroAfterTestsBetweenThreePeers()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSynchroAfterTestsBetweenThreePeers -->
        <test-method status="SKIP" signature="testIndirectSynchro(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testIndirectSynchro" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="provideDataForIndirectSynchro" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testSynchroAfterTestsBetweenThreePeers" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testIndirectSynchro(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testIndirectSynchro(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIndirectSynchro -->
        <test-method status="SKIP" signature="testIndirectSynchroWithIndirectConnection(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testIndirectSynchroWithIndirectConnection" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="testSynchroAfterIndirectTestsBetweenPeers" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testIndirectSynchro" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testIndirectSynchroWithIndirectConnection(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testIndirectSynchroWithIndirectConnection(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIndirectSynchroWithIndirectConnection -->
        <test-method status="SKIP" signature="testSynchroAfterIndirectTestsBetweenPeers()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testSynchroAfterIndirectTestsBetweenPeers" duration-ms="0" started-at="2017-07-05T14:13:37Z" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testIndirectSynchro" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testSynchroAfterIndirectTestsBetweenPeers()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testSynchroAfterIndirectTestsBetweenPeers()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSynchroAfterIndirectTestsBetweenPeers -->
        <test-method status="SKIP" signature="testSynchroAfterPostIndirectTestsBetweenPeers()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testSynchroAfterPostIndirectTestsBetweenPeers" duration-ms="0" started-at="2017-07-05T14:13:37Z" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testIndirectSynchroWithIndirectConnection" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testSynchroAfterPostIndirectTestsBetweenPeers()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testSynchroAfterPostIndirectTestsBetweenPeers()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSynchroAfterPostIndirectTestsBetweenPeers -->
        <test-method status="SKIP" signature="testTransactionBetweenTwoPeers(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testTransactionBetweenTwoPeers" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="testSynchroAfterPostIndirectTestsBetweenPeers" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testIndirectSynchroWithIndirectConnection" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionBetweenTwoPeers(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionBetweenTwoPeers(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionBetweenTwoPeers -->
        <test-method status="SKIP" signature="testTransactionBetweenThreePeers(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testTransactionBetweenThreePeers" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="provideDataForTransactionBetweenThreePeers" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionBetweenTwoPeers" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionBetweenThreePeers(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionBetweenThreePeers(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionBetweenThreePeers -->
        <test-method status="SKIP" signature="testTransactionSynchros(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testTransactionSynchros" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="provideDataForTransactionSynchros" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionBetweenThreePeers" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionSynchros(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionSynchros(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionSynchros -->
        <test-method status="SKIP" signature="testTransactionSynchrosWithIndirectConnection(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testTransactionSynchrosWithIndirectConnection" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="provideDataForTransactionSynchrosWithIndirectConnection" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionSynchros" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnection(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnection(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionSynchrosWithIndirectConnection -->
        <test-method status="SKIP" signature="testTransactionSynchrosWithIndirectConnectionThreaded(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testTransactionSynchrosWithIndirectConnectionThreaded" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="provideDataForTransactionSynchrosWithIndirectConnectionThreaded" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnection" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnectionThreaded(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnectionThreaded(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionSynchrosWithIndirectConnectionThreaded -->
        <test-method status="SKIP" signature="testSynchroTransactionTests()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testSynchroTransactionTests" duration-ms="0" started-at="2017-07-05T14:13:37Z" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnectionThreaded" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testSynchroTransactionTests()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testSynchroTransactionTests()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSynchroTransactionTests -->
        <test-method status="SKIP" signature="addNewPeer()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="addNewPeer" duration-ms="0" started-at="2017-07-05T14:13:37Z" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionBetweenTwoPeers, com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnection, com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnectionThreaded, com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionSynchros, com.distrimind.ood.database.TestDecentralizedDatabase.testSynchroTransactionTests, com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionBetweenThreePeers" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.addNewPeer()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.addNewPeer()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewPeer -->
        <test-method status="SKIP" signature="testSynchroBetweenTwoPeers2(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testSynchroBetweenTwoPeers2" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="provideDataForSynchroBetweenTwoPeers" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.addNewPeer" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testSynchroBetweenTwoPeers2(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testSynchroBetweenTwoPeers2(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSynchroBetweenTwoPeers2 -->
        <test-method status="SKIP" signature="testSynchroBetweenThreePeers2(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testSynchroBetweenThreePeers2" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="provideDataSynchroBetweenThreePeers" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testSynchroBetweenTwoPeers2" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testSynchroBetweenThreePeers2(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testSynchroBetweenThreePeers2(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSynchroBetweenThreePeers2 -->
        <test-method status="SKIP" signature="testIndirectSynchro2(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testIndirectSynchro2" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="provideDataForIndirectSynchro" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testSynchroBetweenThreePeers2" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testIndirectSynchro2(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testIndirectSynchro2(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIndirectSynchro2 -->
        <test-method status="SKIP" signature="testIndirectSynchroWithIndirectConnection2(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testIndirectSynchroWithIndirectConnection2" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="provideDataForIndirectSynchroWithIndirectConnection" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testIndirectSynchro2" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testIndirectSynchroWithIndirectConnection2(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testIndirectSynchroWithIndirectConnection2(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIndirectSynchroWithIndirectConnection2 -->
        <test-method status="SKIP" signature="testTransactionBetweenTwoPeers2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testTransactionBetweenTwoPeers2" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="provideDataForTransactionBetweenTwoPeers" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testIndirectSynchroWithIndirectConnection2" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionBetweenTwoPeers2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionBetweenTwoPeers2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionBetweenTwoPeers2 -->
        <test-method status="SKIP" signature="testTransactionBetweenTwoPeers3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testTransactionBetweenTwoPeers3" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="provideDataForTransactionBetweenTwoPeers" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testIndirectSynchroWithIndirectConnection2" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionBetweenTwoPeers3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionBetweenTwoPeers3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionBetweenTwoPeers3 -->
        <test-method status="SKIP" signature="testTransactionBetweenThreePeers2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testTransactionBetweenThreePeers2" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="provideDataForTransactionBetweenThreePeers" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionBetweenTwoPeers2" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionBetweenThreePeers2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionBetweenThreePeers2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionBetweenThreePeers2 -->
        <test-method status="SKIP" signature="testTransactionBetweenThreePeers3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testTransactionBetweenThreePeers3" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="provideDataForTransactionBetweenThreePeers" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionBetweenTwoPeers3" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionBetweenThreePeers3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionBetweenThreePeers3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionBetweenThreePeers3 -->
        <test-method status="SKIP" signature="testTransactionSynchros2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testTransactionSynchros2" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="provideDataForTransactionSynchros" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionBetweenThreePeers2" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionSynchros2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionSynchros2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionSynchros2 -->
        <test-method status="SKIP" signature="testTransactionSynchros3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testTransactionSynchros3" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="provideDataForTransactionSynchros" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionBetweenThreePeers3" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionSynchros3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionSynchros3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionSynchros3 -->
        <test-method status="SKIP" signature="testTransactionSynchrosWithIndirectConnection2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testTransactionSynchrosWithIndirectConnection2" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="provideDataForTransactionSynchrosWithIndirectConnection" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionSynchros2" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnection2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnection2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionSynchrosWithIndirectConnection2 -->
        <test-method status="SKIP" signature="testTransactionSynchrosWithIndirectConnection3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testTransactionSynchrosWithIndirectConnection3" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="provideDataForTransactionSynchrosWithIndirectConnection" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionSynchros3" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnection3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnection3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionSynchrosWithIndirectConnection3 -->
        <test-method status="SKIP" signature="testTransactionSynchrosWithIndirectConnectionThreaded2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testTransactionSynchrosWithIndirectConnectionThreaded2" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="provideDataForTransactionSynchrosWithIndirectConnectionThreaded" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnection2" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnectionThreaded2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnectionThreaded2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionSynchrosWithIndirectConnectionThreaded2 -->
        <test-method status="SKIP" signature="testTransactionSynchrosWithIndirectConnectionThreaded3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testTransactionSynchrosWithIndirectConnectionThreaded3" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="provideDataForTransactionSynchrosWithIndirectConnectionThreaded" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnection3" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnectionThreaded3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnectionThreaded3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionSynchrosWithIndirectConnectionThreaded3 -->
        <test-method status="SKIP" signature="testSynchroTransactionTests2()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testSynchroTransactionTests2" duration-ms="0" started-at="2017-07-05T14:13:37Z" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnectionThreaded2" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testSynchroTransactionTests2()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testSynchroTransactionTests2()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSynchroTransactionTests2 -->
        <test-method status="SKIP" signature="testSynchroTransactionTests3()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testSynchroTransactionTests3" duration-ms="0" started-at="2017-07-05T14:13:37Z" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnectionThreaded3" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testSynchroTransactionTests3()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testSynchroTransactionTests3()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSynchroTransactionTests3 -->
        <test-method status="SKIP" signature="removeNewPeer()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="removeNewPeer" duration-ms="0" started-at="2017-07-05T14:13:37Z" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testSynchroTransactionTests2" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.removeNewPeer()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.removeNewPeer()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removeNewPeer -->
        <test-method status="SKIP" signature="testSynchroBetweenTwoPeers3(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testSynchroBetweenTwoPeers3" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="provideDataForSynchroBetweenTwoPeers" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.removeNewPeer" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testSynchroBetweenTwoPeers3(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testSynchroBetweenTwoPeers3(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSynchroBetweenTwoPeers3 -->
        <test-method status="SKIP" signature="testSynchroBetweenThreePeers3(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testSynchroBetweenThreePeers3" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="provideDataSynchroBetweenThreePeers" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testSynchroBetweenTwoPeers3" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testSynchroBetweenThreePeers3(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testSynchroBetweenThreePeers3(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSynchroBetweenThreePeers3 -->
        <test-method status="SKIP" signature="testIndirectSynchro3(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testIndirectSynchro3" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="provideDataForIndirectSynchro" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testSynchroBetweenThreePeers3" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testIndirectSynchro3(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testIndirectSynchro3(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIndirectSynchro3 -->
        <test-method status="SKIP" signature="testIndirectSynchroWithIndirectConnection3(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="testIndirectSynchroWithIndirectConnection3" duration-ms="0" started-at="2017-07-05T14:13:37Z" data-provider="provideDataForIndirectSynchroWithIndirectConnection" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testIndirectSynchro3" finished-at="2017-07-05T14:13:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testIndirectSynchroWithIndirectConnection3(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testIndirectSynchroWithIndirectConnection3(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIndirectSynchroWithIndirectConnection3 -->
        <test-method status="PASS" signature="unloadDatabase()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@5674fb70]" name="unloadDatabase" is-config="true" duration-ms="540" started-at="2017-07-05T14:13:37Z" finished-at="2017-07-05T14:13:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- unloadDatabase -->
      </class> <!-- com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
