<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="30" failed="1" ignored="0" total="33" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="3719" started-at="2017-06-23T15:50:16Z" finished-at="2017-06-23T15:50:20Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="3719" started-at="2017-06-23T15:50:16Z" finished-at="2017-06-23T15:50:20Z">
      <class name="com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase">
        <test-method status="PASS" signature="loadDatabase()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="loadDatabase" is-config="true" duration-ms="2117" started-at="2017-06-23T16:50:16Z" finished-at="2017-06-23T16:50:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadDatabase -->
        <test-method status="PASS" signature="testAddFirstElements()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testAddFirstElements" duration-ms="679" started-at="2017-06-23T16:50:19Z" finished-at="2017-06-23T16:50:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddFirstElements -->
        <test-method status="PASS" signature="cleanPendedEvents()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="cleanPendedEvents" is-config="true" duration-ms="1" started-at="2017-06-23T16:50:19Z" finished-at="2017-06-23T16:50:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanPendedEvents -->
        <test-method status="PASS" signature="testInit()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testInit" duration-ms="219" started-at="2017-06-23T16:50:19Z" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testAddFirstElements" finished-at="2017-06-23T16:50:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInit -->
        <test-method status="PASS" signature="cleanPendedEvents()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="cleanPendedEvents" is-config="true" duration-ms="0" started-at="2017-06-23T16:50:19Z" finished-at="2017-06-23T16:50:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanPendedEvents -->
        <test-method status="FAIL" signature="testAllConnect()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testAllConnect" duration-ms="38" started-at="2017-06-23T16:50:19Z" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testInit" finished-at="2017-06-23T16:50:20Z">
          <exception class="com.distrimind.ood.database.exceptions.DatabaseException">
            <full-stacktrace>
              <![CDATA[com.distrimind.ood.database.exceptions.DatabaseException: 
	at com.distrimind.ood.database.DatabaseWrapper$5.run(DatabaseWrapper.java:1781)
	at com.distrimind.ood.database.DatabaseWrapper.runTransaction(DatabaseWrapper.java:1603)
	at com.distrimind.ood.database.DatabaseWrapper.runSynchronizedTransaction(DatabaseWrapper.java:1766)
	at com.distrimind.ood.database.DatabaseWrapper$DatabaseEventsToSynchronize.exportToOutputStream(DatabaseWrapper.java:756)
	at com.distrimind.ood.database.TestDecentralizedDatabase$DistantDatabaseEvent.<init>(TestDecentralizedDatabase.java:110)
	at com.distrimind.ood.database.TestDecentralizedDatabase.exchangeMessages(TestDecentralizedDatabase.java:640)
	at com.distrimind.ood.database.TestDecentralizedDatabase.connect(TestDecentralizedDatabase.java:678)
	at com.distrimind.ood.database.TestDecentralizedDatabase.connectAllDatabase(TestDecentralizedDatabase.java:694)
	at com.distrimind.ood.database.TestDecentralizedDatabase.testAllConnect(TestDecentralizedDatabase.java:858)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: com.distrimind.ood.database.exceptions.DatabaseException: A Sql exception occurs
	at com.distrimind.ood.database.exceptions.DatabaseException.getDatabaseException(DatabaseException.java:82)
	at com.distrimind.ood.database.Table$3TransactionTmp.run(Table.java:5866)
	at com.distrimind.ood.database.DatabaseWrapper.runTransaction(DatabaseWrapper.java:1684)
	at com.distrimind.ood.database.Table.getListRecordsFromSqlConnection(Table.java:5879)
	at com.distrimind.ood.database.Table.getListRecordsFromSqlConnection(Table.java:5800)
	at com.distrimind.ood.database.Table.getPaginedOrderedRecords(Table.java:2151)
	at com.distrimind.ood.database.Table.getOrderedRecords(Table.java:2115)
	at com.distrimind.ood.database.Table.getOrderedRecords(Table.java:2100)
	at com.distrimind.ood.database.DatabaseTransactionsPerHostTable.exportTransactions(DatabaseTransactionsPerHostTable.java:564)
	at com.distrimind.ood.database.DatabaseWrapper$DatabaseEventsToSynchronize$1.run(DatabaseWrapper.java:761)
	at com.distrimind.ood.database.DatabaseWrapper$DatabaseEventsToSynchronize$1.run(DatabaseWrapper.java:1)
	at com.distrimind.ood.database.DatabaseWrapper$5.run(DatabaseWrapper.java:1777)
	... 33 more
Caused by: java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: COM_DISTRIMIND_OOD_DATABASE_DATABASETRANSACTIONEVENTSTABLE.ID in statement [SELECT COM_DISTRIMIND_OOD_DATABASE_DATABASETRANSACTIONSPERHOSTTABLE.TRANSACTION__COM_DISTRIMIND_OOD_DATABASE_DATABASETRANSACTIONEVENTSTABLE_ID, COM_DISTRIMIND_OOD_DATABASE_DATABASETRANSACTIONSPERHOSTTABLE.HOOK__COM_DISTRIMIND_OOD_DATABASE_DATABASEHOOKSTABLE_ID FROM COM_DISTRIMIND_OOD_DATABASE_DATABASETRANSACTIONSPERHOSTTABLE WHERE COM_DISTRIMIND_OOD_DATABASE_DATABASETRANSACTIONEVENTSTABLE.ID<=?]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source)
	at com.distrimind.ood.database.Table$AbstractReadQuerry.<init>(Table.java:7963)
	at com.distrimind.ood.database.Table$ReadQuerry.<init>(Table.java:7990)
	at com.distrimind.ood.database.Table$3TransactionTmp.run(Table.java:5831)
	... 43 more
Caused by: org.hsqldb.HsqlException: user lacks privilege or object not found: COM_DISTRIMIND_OOD_DATABASE_DATABASETRANSACTIONEVENTSTABLE.ID
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.ExpressionColumn.checkColumnsResolved(Unknown Source)
	at org.hsqldb.QueryExpression.resolve(Unknown Source)
	at org.hsqldb.ParserDQL.compileCursorSpecification(Unknown Source)
	at org.hsqldb.ParserCommand.compilePart(Unknown Source)
	at org.hsqldb.ParserCommand.compileStatement(Unknown Source)
	at org.hsqldb.Session.compileStatement(Unknown Source)
	at org.hsqldb.StatementManager.compile(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 48 more
]]>
            </full-stacktrace>
          </exception> <!-- com.distrimind.ood.database.exceptions.DatabaseException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAllConnect -->
        <test-method status="PASS" signature="cleanPendedEvents()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="cleanPendedEvents" is-config="true" duration-ms="1" started-at="2017-06-23T16:50:20Z" finished-at="2017-06-23T16:50:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanPendedEvents -->
        <test-method status="SKIP" signature="testOldElementsAddedBeforeAddingSynchroSynchronized()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testOldElementsAddedBeforeAddingSynchroSynchronized" duration-ms="0" started-at="2017-06-23T16:50:20Z" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testAllConnect" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testOldElementsAddedBeforeAddingSynchroSynchronized()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testOldElementsAddedBeforeAddingSynchroSynchronized()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOldElementsAddedBeforeAddingSynchroSynchronized -->
        <test-method status="SKIP" signature="testSynchroBetweenTwoPeers(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testSynchroBetweenTwoPeers" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataForSynchroBetweenTwoPeers" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testOldElementsAddedBeforeAddingSynchroSynchronized" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testSynchroBetweenTwoPeers(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testSynchroBetweenTwoPeers(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSynchroBetweenTwoPeers -->
        <test-method status="SKIP" signature="testSynchroBetweenThreePeers(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testSynchroBetweenThreePeers" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataSynchroBetweenThreePeers" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testSynchroBetweenTwoPeers" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testSynchroBetweenThreePeers(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testSynchroBetweenThreePeers(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSynchroBetweenThreePeers -->
        <test-method status="SKIP" signature="testIndirectSynchro(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testIndirectSynchro" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataForIndirectSynchro" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testSynchroBetweenThreePeers" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testIndirectSynchro(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testIndirectSynchro(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIndirectSynchro -->
        <test-method status="SKIP" signature="testIndirectSynchroWithIndirectConnection(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testIndirectSynchroWithIndirectConnection" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataForIndirectSynchroWithIndirectConnection" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testIndirectSynchro" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testIndirectSynchroWithIndirectConnection(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testIndirectSynchroWithIndirectConnection(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIndirectSynchroWithIndirectConnection -->
        <test-method status="SKIP" signature="testTransactionBetweenTwoPeers(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testTransactionBetweenTwoPeers" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataForSynchroBetweenTwoPeers" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testIndirectSynchroWithIndirectConnection" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionBetweenTwoPeers(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionBetweenTwoPeers(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionBetweenTwoPeers -->
        <test-method status="SKIP" signature="testTransactionBetweenThreePeers(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testTransactionBetweenThreePeers" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataForTransactionBetweenThreePeers" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionBetweenTwoPeers" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionBetweenThreePeers(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionBetweenThreePeers(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionBetweenThreePeers -->
        <test-method status="SKIP" signature="testTransactionSynchros(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testTransactionSynchros" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataForTransactionSynchros" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionBetweenThreePeers" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionSynchros(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionSynchros(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionSynchros -->
        <test-method status="SKIP" signature="testTransactionSynchrosWithIndirectConnection(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testTransactionSynchrosWithIndirectConnection" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataForTransactionSynchrosWithIndirectConnection" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionSynchros" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnection(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnection(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionSynchrosWithIndirectConnection -->
        <test-method status="SKIP" signature="testTransactionSynchrosWithIndirectConnectionThreaded(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testTransactionSynchrosWithIndirectConnectionThreaded" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataForTransactionSynchrosWithIndirectConnectionThreaded" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnection" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnectionThreaded(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnectionThreaded(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionSynchrosWithIndirectConnectionThreaded -->
        <test-method status="SKIP" signature="addNewPeer()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="addNewPeer" duration-ms="0" started-at="2017-06-23T16:50:20Z" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionBetweenTwoPeers, com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnection, com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnectionThreaded, com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionSynchros, com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionBetweenThreePeers" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.addNewPeer()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.addNewPeer()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewPeer -->
        <test-method status="SKIP" signature="testSynchroBetweenTwoPeers2(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testSynchroBetweenTwoPeers2" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataForSynchroBetweenTwoPeers" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.addNewPeer" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testSynchroBetweenTwoPeers2(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testSynchroBetweenTwoPeers2(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSynchroBetweenTwoPeers2 -->
        <test-method status="SKIP" signature="testSynchroBetweenThreePeers2(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testSynchroBetweenThreePeers2" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataSynchroBetweenThreePeers" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testSynchroBetweenTwoPeers2" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testSynchroBetweenThreePeers2(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testSynchroBetweenThreePeers2(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSynchroBetweenThreePeers2 -->
        <test-method status="SKIP" signature="testIndirectSynchro2(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testIndirectSynchro2" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataForIndirectSynchro" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testSynchroBetweenThreePeers2" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testIndirectSynchro2(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testIndirectSynchro2(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIndirectSynchro2 -->
        <test-method status="SKIP" signature="testIndirectSynchroWithIndirectConnection2(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testIndirectSynchroWithIndirectConnection2" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataForIndirectSynchroWithIndirectConnection" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testIndirectSynchro2" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testIndirectSynchroWithIndirectConnection2(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testIndirectSynchroWithIndirectConnection2(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIndirectSynchroWithIndirectConnection2 -->
        <test-method status="SKIP" signature="testTransactionBetweenTwoPeers2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testTransactionBetweenTwoPeers2" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataForSynchroBetweenTwoPeers" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testIndirectSynchroWithIndirectConnection2" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionBetweenTwoPeers2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionBetweenTwoPeers2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionBetweenTwoPeers2 -->
        <test-method status="SKIP" signature="testTransactionBetweenTwoPeers3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testTransactionBetweenTwoPeers3" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataForSynchroBetweenTwoPeers" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testIndirectSynchroWithIndirectConnection2" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionBetweenTwoPeers3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionBetweenTwoPeers3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionBetweenTwoPeers3 -->
        <test-method status="SKIP" signature="testTransactionBetweenThreePeers2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testTransactionBetweenThreePeers2" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataForTransactionBetweenThreePeers" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionBetweenTwoPeers2" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionBetweenThreePeers2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionBetweenThreePeers2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionBetweenThreePeers2 -->
        <test-method status="SKIP" signature="testTransactionBetweenThreePeers3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testTransactionBetweenThreePeers3" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataForTransactionBetweenThreePeers" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionBetweenTwoPeers3" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionBetweenThreePeers3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionBetweenThreePeers3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionBetweenThreePeers3 -->
        <test-method status="SKIP" signature="testTransactionSynchros2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testTransactionSynchros2" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataForTransactionSynchros" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionBetweenThreePeers2" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionSynchros2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionSynchros2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionSynchros2 -->
        <test-method status="SKIP" signature="testTransactionSynchros3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testTransactionSynchros3" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataForTransactionSynchros" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionBetweenThreePeers3" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionSynchros3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionSynchros3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionSynchros3 -->
        <test-method status="SKIP" signature="testTransactionSynchrosWithIndirectConnection2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testTransactionSynchrosWithIndirectConnection2" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataForTransactionSynchrosWithIndirectConnection" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionSynchros2" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnection2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnection2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionSynchrosWithIndirectConnection2 -->
        <test-method status="SKIP" signature="testTransactionSynchrosWithIndirectConnection3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testTransactionSynchrosWithIndirectConnection3" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataForTransactionSynchrosWithIndirectConnection" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionSynchros3" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnection3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnection3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionSynchrosWithIndirectConnection3 -->
        <test-method status="SKIP" signature="testTransactionSynchrosWithIndirectConnectionThreaded2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testTransactionSynchrosWithIndirectConnectionThreaded2" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataForTransactionSynchrosWithIndirectConnectionThreaded" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnection2" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnectionThreaded2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnectionThreaded2(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionSynchrosWithIndirectConnectionThreaded2 -->
        <test-method status="SKIP" signature="testTransactionSynchrosWithIndirectConnectionThreaded3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testTransactionSynchrosWithIndirectConnectionThreaded3" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataForTransactionSynchrosWithIndirectConnectionThreaded" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnection3" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnectionThreaded3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnectionThreaded3(boolean, java.util.List)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionSynchrosWithIndirectConnectionThreaded3 -->
        <test-method status="SKIP" signature="removeNewPeer()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="removeNewPeer" duration-ms="0" started-at="2017-06-23T16:50:20Z" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testTransactionSynchrosWithIndirectConnectionThreaded2" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.removeNewPeer()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.removeNewPeer()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removeNewPeer -->
        <test-method status="SKIP" signature="testSynchroBetweenTwoPeers3(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testSynchroBetweenTwoPeers3" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataForSynchroBetweenTwoPeers" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.removeNewPeer" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testSynchroBetweenTwoPeers3(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testSynchroBetweenTwoPeers3(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSynchroBetweenTwoPeers3 -->
        <test-method status="SKIP" signature="testSynchroBetweenThreePeers3(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testSynchroBetweenThreePeers3" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataSynchroBetweenThreePeers" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testSynchroBetweenTwoPeers3" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testSynchroBetweenThreePeers3(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testSynchroBetweenThreePeers3(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSynchroBetweenThreePeers3 -->
        <test-method status="SKIP" signature="testIndirectSynchro3(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testIndirectSynchro3" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataForIndirectSynchro" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testSynchroBetweenThreePeers3" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testIndirectSynchro3(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testIndirectSynchro3(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIndirectSynchro3 -->
        <test-method status="SKIP" signature="testIndirectSynchroWithIndirectConnection3(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="testIndirectSynchroWithIndirectConnection3" duration-ms="0" started-at="2017-06-23T16:50:20Z" data-provider="provideDataForIndirectSynchroWithIndirectConnection" depends-on-methods="com.distrimind.ood.database.TestDecentralizedDatabase.testIndirectSynchro3" finished-at="2017-06-23T16:50:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDecentralizedDatabase.testIndirectSynchroWithIndirectConnection3(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDecentralizedDatabase.testIndirectSynchroWithIndirectConnection3(boolean, boolean, boolean, com.distrimind.ood.database.TableEvent)[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIndirectSynchroWithIndirectConnection3 -->
        <test-method status="PASS" signature="unloadDatabase()[pri:0, instance:com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase@16cbfbed]" name="unloadDatabase" is-config="true" duration-ms="441" started-at="2017-06-23T16:50:20Z" finished-at="2017-06-23T16:50:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- unloadDatabase -->
      </class> <!-- com.distrimind.ood.database.HSQLDBTestDencentralizedDatabase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
